# Generated by Django 5.2.6 on 2025-10-03 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banquet',
            name='image',
        ),
        migrations.CreateModel(
            name='BanquetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banquet_images/')),
                ('banquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.banquet')),
            ],
        ),
    ]
