# Generated by Django 5.2.6 on 2025-10-07 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_banquet_image_banquetimage'),
    ]

    operations = [
    ]
