# website/constants.py

KANPUR_AREAS = KANPUR_AREAS = [
    "Agriculture College",
    "Amour",
    "Anand Nagar",
    "Anwarganj",
    "Aranjhami",
    "Armapore",
    "Armapore Estate",
    "Arya Nagar",
    "Ashok Nagar",
    "Avas Vikas yojna no. 3",
    "B N shukla & sons",
    "Baikuthpur",
    "Bairi",
    "Baraigarh",
    "Barra",
    "Bausar",
    "Behta Gambhirpur",
    "Bhadrsa",
    "Bhairampur",
    "Bharu",
    "Bhauti Pratappur",
    "Bheoli",
    "Bhimsen",
    "Bidhnoo",
    "Bima Vihar",
    "Binour",
    "Birhana Raod",
    "Bisayakpur",
    "Bithoor",
    "Cambridge Road",
    "Chakarpur",
    "Chakeri Aerodrum",
    "Chauki Jarib",
    "Chaurai",
    "Chhatarpur",
    "Colonelganj",
    "Cotton Mill",
    "D O oil mill",
    "Dehli Ujagar",
    "Deosarh",
    "Dhankutti",
    "Elgin Mills",
    "Employeement Exchange",
    "Fahimabad",
    "Farrashkhana",
    "Fatehpur Roshnai",
    "Gayatri Seedh peeth khadeshar",
    "Gazipur",
    "Gopalpur",
    "Govind Nagar",
    "Govind Nagar west",
    "GSVM Medical College",
    "Gwaltoli",
    "Hal Colony",
    "Harchandkhera",
    "Hardauli",
    "Harjinder Nagar",
    "Hathigaon",
    "Hatia",
    "Hbti",
    "Hns Nagar",
    "Indira Nagar",
    "Industrial Estate",
    "Itra",
    "J K puri",
    "Jamu",
    "Jawahar Nagar",
    "Jugrajpur",
    "Juhi Colony",
    "K M street",
    "K P university",
    "Kadari Champatpur",
    "Kaindha",
    "Kalyanpur",
    "Kamlapur",
    "Kanpur",
    "Kanpur Cantt.",
    "Kanpur Chowk",
    "Kanpur Court",
    "Kanpur West",
    "Karbigvan",
    "Kasigaon",
    "Kathara",
    "Katherua",
    "Kathongar",
    "Kaushalpuri",
    "Khapra Mohal",
    "Kheora",
    "Kidwai Nagar",
    "Krishna Nagar",
    "Kudani",
    "Kulgaon",
    "Maharajpur",
    "Maholi",
    "Mahua Gaon",
    "Majhawan",
    "Mandhana",
    "Mardanpur",
    "Meerpur Cantt",
    "Motijheel",
    "Muir Mill",
    "Munshipurwa",
    "N C line",
    "N H road",
    "Napier Road",
    "Naramau",
    "Narona Exchange",
    "Narwal",
    "Nasra",
    "Naveen Market",
    "Naveen Nagar",
    "Nawabganj",
    "Nayaganj",
    "New Pac lines",
    "Nirala Nagar",
    "Nsi",
    "Oe Factory",
    "Pachor",
    "Palhepur",
    "Pali Bhogipur",
    "Panki",
    "Panki Ganga ganj",
    "Parasadepur",
    "Parsauli",
    "Pem",
    "Philkhana",
    "Phuphuwar",
    "Pipergaon",
    "Prempur Badagaon",
    "Purana Kanpur",
    "Purwameer",
    "R K nagar",
    "Rbi Colony",
    "Railganj",
    "Raipur Kukhat",
    "Ramaipur",
    "Rambagh",
    "Rania",
    "Rasulpur Umra",
    "Ratan Lal nagar",
    "Rawatpur",
    "Rooma",
    "Ramadevi",
    "S C mills",
    "Sachendi",
    "Saketpuri",
    "Salempur",
    "Sanigawan",
    "Sapai",
    "Sarh",
    "Sarsaul",
    "Sarvodaya Nagar",
    "Sawaijpur",
    "Semarjhal",
    "Senpara Paschim",
    "Shivaji Nagar",
    "Shyam Nagar",
    "Sirhi Itra",
    "Sisamau",
    "Subhauli",
    "Swarup Nagar",
    "T P nagar",
    "Tatya Ganj",
    "Taudhakpur",
    "Tikra",
    "Tilsahari",
    "Udaipur",
    "Udyog Nagar",
    "Vijai Nagar",
    "Yashoda Nagar",
]
